SET SQLBLANKLINES ON

PROMPT ============================================================
PROMPT  Update 4 migration - run once on an existing Update 3 schema
PROMPT ============================================================

ALTER TABLE STORAGE_MANAGER DROP CONSTRAINT UQ_MANAGER_EMPLOYEEID;
ALTER TABLE STORAGE_MANAGER DROP CONSTRAINT UQ_MANAGER_CERT;
ALTER TABLE STORAGE_MANAGER DROP (EmployeeID, HireDate, CertificationNo);

ALTER TABLE HARVEST_BATCH DROP CONSTRAINT CK_BATCH_GRADE;
ALTER TABLE HARVEST_BATCH DROP CONSTRAINT CK_BATCH_MOISTURE;
ALTER TABLE HARVEST_BATCH DROP (QualityGrade, MoisturePercentage);

ALTER TABLE FARM ADD (
  VerificationStatus VARCHAR2(10 CHAR) DEFAULT 'PENDING',
  VerificationRequestedAt DATE DEFAULT SYSDATE,
  VerificationReviewedAt DATE,
  VerifiedByAdminID NUMBER(10)
);
UPDATE FARM
   SET VerificationStatus = 'PENDING',
       VerificationRequestedAt = NVL(VerificationRequestedAt, SYSDATE);
ALTER TABLE FARM MODIFY (VerificationStatus NOT NULL, VerificationRequestedAt NOT NULL);
ALTER TABLE FARM ADD CONSTRAINT FK_FARM_VERIFIER
  FOREIGN KEY (VerifiedByAdminID) REFERENCES ADMIN_STAFF (AdminID);
ALTER TABLE FARM ADD CONSTRAINT CK_FARM_VERIFICATION
  CHECK (VerificationStatus IN ('PENDING','VERIFIED','REJECTED'));
ALTER TABLE FARM ADD CONSTRAINT CK_FARM_VERIFICATION_SHAPE CHECK (
  (VerificationStatus = 'VERIFIED' AND VerificationReviewedAt IS NOT NULL AND VerifiedByAdminID IS NOT NULL)
  OR VerificationStatus <> 'VERIFIED'
);

ALTER TABLE STORAGE_UNIT ADD (LocationTag VARCHAR2(120 CHAR));
UPDATE STORAGE_UNIT su
   SET LocationTag = 'Unit ' || su.UnitNo || ' - ' ||
       (SELECT NVL(w.Address, w.WarehouseName) FROM WAREHOUSE w
         WHERE w.WarehouseID = su.WarehouseID);
ALTER TABLE STORAGE_UNIT MODIFY (LocationTag NOT NULL);
ALTER TABLE STORAGE_UNIT ADD CONSTRAINT UQ_UNIT_LOCATION UNIQUE (WarehouseID, LocationTag);

ALTER TABLE STORES DROP CONSTRAINT CK_STORES_STATUS;
ALTER TABLE STORES ADD CONSTRAINT CK_STORES_STATUS CHECK (AllocationStatus IN
  ('PENDING_ACCEPT','COUNTERED','IN_TRANSIT','ACTIVE','PENDING_RELEASE','COMPLETED','REJECTED','CANCELLED'));

ALTER TABLE TRANSPORT_REQUEST MODIFY (SaleOrderID NULL);
ALTER TABLE TRANSPORT_REQUEST ADD (
  RequestType VARCHAR2(20 CHAR) DEFAULT 'SALE_DELIVERY',
  AllocationID NUMBER(10)
);
UPDATE TRANSPORT_REQUEST SET RequestType = 'SALE_DELIVERY' WHERE RequestType IS NULL;
ALTER TABLE TRANSPORT_REQUEST MODIFY (RequestType NOT NULL);
ALTER TABLE TRANSPORT_REQUEST ADD CONSTRAINT FK_TRANSPORT_ALLOCATION
  FOREIGN KEY (AllocationID) REFERENCES STORES (AllocationID) ON DELETE CASCADE;
ALTER TABLE TRANSPORT_REQUEST ADD CONSTRAINT UQ_TRANSPORT_ALLOCATION UNIQUE (AllocationID);
ALTER TABLE TRANSPORT_REQUEST ADD CONSTRAINT CK_TRANSPORT_TYPE
  CHECK (RequestType IN ('SALE_DELIVERY','STORAGE_INBOUND'));
ALTER TABLE TRANSPORT_REQUEST ADD CONSTRAINT CK_TRANSPORT_SHAPE CHECK (
  (RequestType = 'SALE_DELIVERY' AND SaleOrderID IS NOT NULL AND AllocationID IS NULL)
  OR (RequestType = 'STORAGE_INBOUND' AND AllocationID IS NOT NULL)
);

COMMIT;

PROMPT Update 4 table migration complete. Re-run 04_views.sql and 05_plsql_layer.sql next.
