import { useCallback, useEffect, useState } from 'react';
import { api } from '../../api/client';
import { date, number } from '../../utils/format';

export default function AdminDashboard() {
  const [summary,setSummary]=useState(null), [users,setUsers]=useState([]), [prices,setPrices]=useState([]), [complaints,setComplaints]=useState([]), [logistics,setLogistics]=useState({requests:[],vehicles:[],personnel:[]}), [assignment,setAssignment]=useState({transportId:'',vehicleId:'',personnelId:''}), [error,setError]=useState('');
  const load=useCallback(async()=>{try{setError('');const [s,u,p,c,l]=await Promise.all([api('/admin/dashboard'),api('/admin/users'),api('/admin/prices'),api('/admin/complaints'),api('/admin/logistics')]);setSummary(s);setUsers(u);setPrices(p);setComplaints(c);setLogistics(l);}catch(e){setError(e.message);}},[]);
  useEffect(()=>{load();},[load]);
  async function userStatus(id,status){try{await api(`/admin/users/${id}/status`,{method:'PATCH',body:{status}});await load();}catch(e){setError(e.message);}}
  async function complaintStatus(id,status){try{await api(`/admin/complaints/${id}`,{method:'PATCH',body:{status}});await load();}catch(e){setError(e.message);}}
  async function assign(e){e.preventDefault();try{await api('/admin/logistics/assign',{method:'POST',body:assignment});setAssignment({transportId:'',vehicleId:'',personnelId:''});await load();}catch(err){setError(err.message);}}
  return <div className="page">
    <h1>Administration</h1><p className="muted">Platform activity, users, prices and complaint queue</p>
    {error&&<p className="error" role="alert">{error}</p>}
    {summary&&<div className="stats"><Stat label="Users" value={summary.USERS}/><Stat label="Active batches" value={summary.ACTIVEBATCHES}/><Stat label="Orders" value={summary.ORDERS}/><Stat label="Open complaints" value={summary.OPENCOMPLAINTS}/></div>}
    <h2>Assign transport</h2>{!logistics.requests.length?<p className="muted">No pending transport requests.</p>:<form className="inline-form" onSubmit={assign}><label>Request<select required value={assignment.transportId} onChange={e=>setAssignment({...assignment,transportId:e.target.value})}><option value="">Select request</option>{logistics.requests.map(r=><option key={r.TRANSPORTID} value={r.TRANSPORTID}>#{r.TRANSPORTID} · Order #{r.SALEORDERID}</option>)}</select></label><label>Vehicle<select required value={assignment.vehicleId} onChange={e=>setAssignment({...assignment,vehicleId:e.target.value})}><option value="">Select vehicle</option>{logistics.vehicles.map(v=><option key={v.VEHICLEID} value={v.VEHICLEID}>{v.VEHICLENO} · {number(v.CAPACITY)} kg</option>)}</select></label><label>Personnel<select required value={assignment.personnelId} onChange={e=>setAssignment({...assignment,personnelId:e.target.value})}><option value="">Select personnel</option>{logistics.personnel.map(p=><option key={p.PERSONNELID} value={p.PERSONNELID}>{p.NAME} · {p.LICENSENO}</option>)}</select></label><button type="submit">Assign</button></form>}
    <h2>Users</h2><div className="table-wrap"><table><thead><tr><th>Name</th><th>Role</th><th>Email</th><th>Status</th><th>Action</th></tr></thead><tbody>{users.map(u=><tr key={u.USERID}><td>{u.FIRSTNAME} {u.LASTNAME}</td><td>{u.ROLE}</td><td>{u.EMAIL}</td><td><span className="tag">{u.STATUS}</span></td><td><select aria-label={`Status for ${u.EMAIL}`} value={u.STATUS} onChange={e=>userStatus(u.USERID,e.target.value)}><option>ACTIVE</option><option>BLOCKED</option><option>INACTIVE</option></select></td></tr>)}</tbody></table></div>
    <h2>Recent daily prices</h2><div className="table-wrap"><table><thead><tr><th>Date</th><th>Crop</th><th>Arat</th><th className="num">Price/kg</th><th>Range</th></tr></thead><tbody>{prices.map((p,i)=><tr key={`${p.CROPID}-${p.ARATID}-${p.PRICEDATE}-${i}`}><td>{date(p.PRICEDATE)}</td><td>{p.CROPNAME}</td><td>{p.ARATNAME}</td><td className="num">৳{number(p.PRICEPERKG)}</td><td>৳{number(p.MINPRICE)}–{number(p.MAXPRICE)}</td></tr>)}</tbody></table></div>
    <h2>Complaints</h2>{!complaints.length?<p className="muted">No complaints.</p>:<div className="card-grid">{complaints.map(c=><article className="card" key={c.COMPLAINTID}><div className="row"><strong>#{c.COMPLAINTID} · Order #{c.SALEORDERID}</strong><span className="tag">{c.STATUS}</span></div><p>{c.COMPLAINTTYPE}</p><p className="muted">{c.DESCRIPTION}</p><div className="actions"><button className="small" onClick={()=>complaintStatus(c.COMPLAINTID,'IN_REVIEW')}>Review</button><button className="small" onClick={()=>complaintStatus(c.COMPLAINTID,'RESOLVED')}>Resolve</button><button className="small secondary" onClick={()=>complaintStatus(c.COMPLAINTID,'REJECTED')}>Reject</button></div></article>)}</div>}
  </div>;
}
function Stat({label,value}){return <div className="stat"><span className="stat-label">{label}</span><span className="stat-value">{number(value)}</span></div>}
